CREATE TABLE IF NOT EXISTS users (id BIGSERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token TEXT UNIQUE NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS products (id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,price NUMERIC(12,2) NOT NULL,stock INT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS cart_items (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INT NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id, product_id));
CREATE TABLE IF NOT EXISTS orders (id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id),address TEXT NOT NULL,amount NUMERIC(12,2) NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS order_items (id BIGSERIAL PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL,product_title TEXT NOT NULL,price NUMERIC(12,2) NOT NULL,quantity INT NOT NULL);
INSERT INTO products(title, price, stock)
SELECT * FROM (VALUES ('Wireless Earbuds Pro', 199.00, 120),('Mechanical Keyboard 87', 329.00, 80),('Portable SSD 1TB', 599.00, 60),('Smart Lamp', 149.00, 200)) AS v(title, price, stock)
WHERE NOT EXISTS (SELECT 1 FROM products);
