#!/usr/bin/env bash
set -euo pipefail

repo_root="$(git rev-parse --show-toplevel)"
cd "${repo_root}"

mode="${1:-check}"
allow_regex="${FRONTEND_DRIFT_ALLOW_REGEX:-^$}"
protected_regex='^ecommerce_app/frontend/src/(App\.tsx|styles\.css)$'
report_path="${FRONTEND_DRIFT_REPORT:-}"
isolation_script_path="${FRONTEND_DRIFT_ISOLATION_SCRIPT:-}"

collect_changes() {
  {
    git diff --name-only
    git diff --cached --name-only
    git ls-files --others --exclude-standard
  } | sed '/^$/d' | sort -u
}

changed="$(collect_changes | grep '^ecommerce_app/frontend/' || true)"
blocked=""
if [[ -n "${changed}" ]]; then
  blocked="$(printf '%s\n' "${changed}" | grep -E "${protected_regex}" | grep -Ev "${allow_regex}" || true)"
fi
target_only="$(printf '%s\n' "${changed}" | grep -vxFf <(printf '%s\n' "${blocked}") || true)"

emit_report() {
  [[ -z "${report_path}" ]] && return 0
  python3 - "$report_path" "$mode" "$allow_regex" "$protected_regex" "$changed" "$blocked" "$target_only" "$isolation_script_path" <<'PY'
import json, sys
path, mode, allow, protected, changed, blocked, target_only, isolation_script = sys.argv[1:9]
changed_list = [x for x in changed.splitlines() if x.strip()]
blocked_list = [x for x in blocked.splitlines() if x.strip()]
target_list = [x for x in target_only.splitlines() if x.strip()]
target_cmd = "git add " + " ".join(target_list) if target_list else ""
payload = {
    "mode": mode,
    "allow_regex": allow,
    "protected_regex": protected,
    "changed_files": changed_list,
    "blocked_files": blocked_list,
    "status": "blocked" if blocked_list else "ok",
    "suggestions": [
        "set FRONTEND_DRIFT_ALLOW_REGEX for intentional entrypoint edits",
        "run: bash ecommerce_app/scripts/frontend_drift_guard.sh isolate",
    ],
    "isolation_script": isolation_script,
    "target_only_files": target_list,
    "target_commit_commands": [
        "git status --short",
        target_cmd,
        'git commit -m "iter-xx: <scope>"',
    ] if target_cmd else [
        "git status --short",
        "# no target frontend files remain after isolating protected drift",
    ],
}
with open(path, "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)
PY
}

generate_isolation_script() {
  [[ -z "${isolation_script_path}" ]] && return 0
  if [[ -z "${blocked}" ]]; then
    rm -f "${isolation_script_path}"
    return 0
  fi
  mkdir -p "$(dirname "${isolation_script_path}")"
  {
    printf '#!/usr/bin/env bash\n'
    printf 'set -euo pipefail\n\n'
    printf 'repo_root="$(git rev-parse --show-toplevel)"\n'
    printf 'cd "${repo_root}"\n\n'
    printf '# Auto-generated by frontend_drift_guard.sh\n'
    printf '# Unstage protected drift files before creating focused commit.\n'
    while IFS= read -r p; do
      [[ -z "${p}" ]] && continue
      printf 'git restore --staged -- %q >/dev/null 2>&1 || true\n' "${p}"
    done <<< "${blocked}"
    printf '\n'
    if [[ -n "${target_only}" ]]; then
      printf '# Stage only target frontend files for this commit scope.\n'
      printf 'git add'
      while IFS= read -r p; do
        [[ -z "${p}" ]] && continue
        printf ' %q' "${p}"
      done <<< "${target_only}"
      printf '\n'
      printf 'echo "Suggested commit: git commit -m \\"iter-xx: frontend <scope>\\""\n'
    else
      printf 'echo "No target frontend files remain after isolating protected drift."\n'
    fi
    printf '\n'
    printf 'echo "Protected drift files unstaged. Continue with target-scope commit."\n'
    printf 'echo "Check status: git status --short"\n'
  } > "${isolation_script_path}"
  chmod +x "${isolation_script_path}"
}

if [[ -z "${changed}" ]]; then
  generate_isolation_script
  emit_report
  echo "[frontend-drift-guard] ok: no frontend drift"
  exit 0
fi

if [[ -z "${blocked}" ]]; then
  generate_isolation_script
  emit_report
  echo "[frontend-drift-guard] ok"
  exit 0
fi

generate_isolation_script

if [[ "${mode}" == "isolate" ]]; then
  printf '[frontend-drift-guard] isolate: unstage protected drift paths\n'
  while IFS= read -r p; do
    [[ -z "${p}" ]] && continue
    git restore --staged -- "${p}" >/dev/null 2>&1 || true
  done <<< "${blocked}"
  emit_report
  echo "[frontend-drift-guard] protected paths were unstaged"
  exit 0
fi

emit_report
echo "[frontend-drift-guard] blocked protected frontend drift detected:"
printf '%s\n' "${blocked}"
echo "[frontend-drift-guard] set FRONTEND_DRIFT_ALLOW_REGEX to allow intentional entrypoint updates"
echo "[frontend-drift-guard] or run: bash ecommerce_app/scripts/frontend_drift_guard.sh isolate"
if [[ -n "${isolation_script_path}" ]]; then
  echo "[frontend-drift-guard] generated isolation script: ${isolation_script_path}"
fi
exit 1
